[package]
name = "nexus-pro"
version = "0.1.1"
edition = "2021"

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = "2"

[[bin]]
name = "nexus-pro"
path = "src/main.rs"
