[package]
name = "nexus-tauri"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = "2"

[[bin]]
name = "nexus-ide"
path = "src/main.rs"
